"""
CIVORA - NLP Complaint Classifier
FastAPI Microservice

Exposes a REST endpoint to classify civic complaints.
Used by the Node.js backend for integration.

Run:
    uvicorn app:app --reload --port 8000

Docs (auto-generated by FastAPI):
    http://localhost:8000/docs
"""

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field
from predict import classify

app = FastAPI(
    title       = "CIVORA NLP Classifier",
    description = "Classifies civic complaints into department categories.",
    version     = "1.0.0",
)


# ── Request / Response schemas ─────────────────────────────────────────────────
class ComplaintRequest(BaseModel):
    complaint: str = Field(
        ...,
        min_length = 5,
        example    = "There is a huge pothole on MG Road near the bus stop",
        description = "Raw complaint text submitted by the citizen",
    )


class ClassificationResponse(BaseModel):
    category   : str
    confidence : float
    keywords   : list[str]
    all_scores : dict[str, float]


# ── Endpoints ──────────────────────────────────────────────────────────────────
@app.get("/", tags=["Health"])
def health_check():
    return {"status": "ok", "service": "CIVORA NLP Classifier"}


@app.post("/classify", response_model=ClassificationResponse, tags=["Classification"])
def classify_complaint(body: ComplaintRequest):
    """
    Classify a civic complaint text into one of:
    **PWD | Sanitation | Water Supply | Drainage | Electricity | Other**
    """
    try:
        result = classify(body.complaint)
        return result
    except FileNotFoundError as e:
        raise HTTPException(status_code=503, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Classification failed: {str(e)}")
